CFLAGS=-g -Wall
LDLIBS=-lpng
all: rgb565_to_argb8888 argb8888_to_bmp bmp_to_argb8888 argb8888_to_rgb565 \
argb8888_to_argb565 printBmpHdr argb8888_to_png

.PHONY:
clean:
	$(RM) *.o *~  rgb565_to_argb8888 argb8888_to_bmp bmp_to_argb8888 \
argb8888_to_rgb565 argb8888_to_argb565 printBmpHdr argb8888_to_png
